italian_names = [
    "Afghanistan", "Albania", "Algeria", "Andorra",
    "Angola", "Antigua e Barbuda", "Arabia Saudita", "Argentina",
    "Armenia", "Australia", "Austria", "Azerbaigian",
    "Bahamas", "Bahrein", "Bangladesh", "Barbados",
    "Belgio", "Belize", "Benin", "Bhutan",
    "Bielorussia", "Birmania", "Bolivia", "Bosnia ed Erzegovina",
    "Botswana", "Brasile", "Brunei", "Bulgaria",
    "Burkina Faso", "Burundi", "Cambogia", "Camerun",
    "Canada", "Capo Verde", "Ciad", "Cile",
    "Cina", "Cipro", "Colombia", "Comore",
    "Corea del Nord", "Corea del Sud", "Costa d'Avorio", "Costa Rica",
    "Croazia", "Cuba", "Danimarca", "Dominica",
    "Ecuador", "Egitto", "El Salvador", "Emirati Arabi Uniti",
    "Eritrea", "Estonia", "Eswatini", "Etiopia",
    "Figi", "Filippine", "Finlandia", "Francia",
    "Gabon", "Gambia", "Georgia", "Germania",
    "Ghana", "Giamaica", "Giappone", "Gibuti",
    "Giordania", "Grecia", "Grenada", "Guatemala",
    "Guinea", "Guinea-Bissau", "Guinea Equatoriale", "Guyana",
    "Haiti", "Honduras", "India", "Indonesia",
    "Iran", "Iraq", "Irlanda", "Islanda",
    "Israele", "Italia", "Kazakistan", "Kenya",
    "Kirghizistan", "Kiribati", "Kuwait", "Laos",
    "Lesotho", "Lettonia", "Libano", "Liberia",
    "Libia", "Liechtenstein", "Lituania", "Lussemburgo",
    "Macedonia del Nord", "Madagascar", "Malawi", "Malaysia",
    "Maldive", "Mali", "Malta", "Marocco",
    "Isole Marshall", "Mauritania", "Mauritius", "Messico",
    "Micronesia", "Moldavia", "Monaco", "Mongolia",
    "Montenegro", "Mozambico", "Namibia", "Nauru",
    "Nepal", "Nicaragua", "Niger", "Nigeria",
    "Norvegia", "Nuova Zelanda", "Oman", "Paesi Bassi",
    "Pakistan", "Palau", "Panama", "Papua Nuova Guinea",
    "Paraguay", "Perù", "Polonia", "Portogallo",
    "Qatar", "Regno Unito", "Repubblica Centrafricana", "Repubblica Ceca",
    "Repubblica Democratica del Congo", "Repubblica del Congo", "Repubblica Dominicana", "Romania",
    "Ruanda", "Russia", "Saint Kitts e Nevis", "Saint Lucia",
    "Saint Vincent e Grenadine", "Samoa", "San Marino", "Santa Sede",
    "São Tomé e Príncipe", "Senegal", "Serbia", "Seychelles",
    "Sierra Leone", "Singapore", "Siria", "Slovacchia",
    "Slovenia", "Somalia", "Spagna", "Sri Lanka",
    "Stati Uniti d'America", "Sudafrica", "Sudan", "Sudan del Sud",
    "Suriname", "Svezia", "Svizzera", "Tagikistan",
    "Taiwan", "Tanzania", "Thailandia", "Timor Est",
    "Togo", "Tonga", "Trinidad e Tobago", "Tunisia",
    "Turchia", "Turkmenistan", "Tuvalu", "Ucraina",
    "Uganda", "Ungheria", "Uruguay", "Uzbekistan",
    "Vanuatu", "Venezuela", "Vietnam", "Yemen",
    "Zambia", "Zimbabwe",
]

italian_names_lower = [
    "afghanistan", "albania", "algeria", "andorra",
    "angola", "antigua e barbuda", "arabia saudita", "argentina",
    "armenia", "australia", "austria", "azerbaigian",
    "bahamas", "bahrein", "bangladesh", "barbados",
    "belgio", "belize", "benin", "bhutan",
    "bielorussia", "birmania", "bolivia", "bosnia ed erzegovina",
    "botswana", "brasile", "brunei", "bulgaria",
    "burkina faso", "burundi", "cambogia", "camerun",
    "canada", "capo verde", "ciad", "cile",
    "cina", "cipro", "colombia", "comore",
    "corea del nord", "corea del sud", "costa d'avorio", "costa rica",
    "croazia", "cuba", "danimarca", "dominica",
    "ecuador", "egitto", "el salvador", "emirati arabi uniti",
    "eritrea", "estonia", "eswatini", "etiopia",
    "figi", "filippine", "finlandia", "francia",
    "gabon", "gambia", "georgia", "germania",
    "ghana", "giamaica", "giappone", "gibuti",
    "giordania", "grecia", "grenada", "guatemala",
    "guinea", "guinea-bissau", "guinea equatoriale", "guyana",
    "haiti", "honduras", "india", "indonesia",
    "iran", "iraq", "irlanda", "islanda",
    "israele", "italia", "kazakistan", "kenya",
    "kirghizistan", "kiribati", "kuwait", "laos",
    "lesotho", "lettonia", "libano", "liberia",
    "libia", "liechtenstein", "lituania", "lussemburgo",
    "macedonia del nord", "madagascar", "malawi", "malaysia",
    "maldive", "mali", "malta", "marocco",
    "isole marshall", "mauritania", "mauritius", "messico",
    "micronesia", "moldavia", "monaco", "mongolia",
    "montenegro", "mozambico", "namibia", "nauru",
    "nepal", "nicaragua", "niger", "nigeria",
    "norvegia", "nuova zelanda", "oman", "paesi bassi",
    "pakistan", "palau", "panama", "papua nuova guinea",
    "paraguay", "perù", "polonia", "portogallo",
    "qatar", "regno unito", "repubblica centrafricana", "repubblica ceca",
    "repubblica democratica del congo", "repubblica del congo", "repubblica dominicana", "romania",
    "ruanda", "russia", "saint kitts e nevis", "saint lucia",
    "saint vincent e grenadine", "samoa", "san marino", "santa sede",
    "são tomé e príncipe", "senegal", "serbia", "seychelles",
    "sierra leone", "singapore", "siria", "slovacchia",
    "slovenia", "somalia", "spagna", "sri lanka",
    "stati uniti d'america", "sudafrica", "sudan", "sudan del sud",
    "suriname", "svezia", "svizzera", "tagikistan",
    "taiwan", "tanzania", "thailandia", "timor est",
    "togo", "tonga", "trinidad e tobago", "tunisia",
    "turchia", "turkmenistan", "tuvalu", "ucraina",
    "uganda", "ungheria", "uruguay", "uzbekistan",
    "vanuatu", "venezuela", "vietnam", "yemen",
    "zambia", "zimbabwe"
]


english_names = [
    "Afghanistan", "Albania", "Algeria", "Andorra",
    "Angola", "Antigua and Barbuda", "Saudi Arabia", "Argentina",
    "Armenia", "Australia", "Austria", "Azerbaijan",
    "Bahamas", "Bahrain", "Bangladesh", "Barbados",
    "Belgium", "Belize", "Benin", "Bhutan",
    "Belarus", "Myanmar", "Bolivia", "Bosnia and Herzegovina",
    "Botswana", "Brazil", "Brunei", "Bulgaria",
    "Burkina Faso", "Burundi", "Cambodia", "Cameroon",
    "Canada", "Cape Verde", "Chad", "Chile",
    "China", "Cyprus", "Colombia", "Comoros",
    "North Korea", "South Korea", "Ivory Coast", "Costa Rica",
    "Croatia", "Cuba", "Denmark", "Dominica",
    "Ecuador", "Egypt", "El Salvador", "United Arab Emirates",
    "Eritrea", "Estonia", "Eswatini", "Ethiopia",
    "Fiji", "Philippines", "Finland", "France",
    "Gabon", "Gambia", "Georgia", "Germany",
    "Ghana", "Jamaica", "Japan", "Djibouti",
    "Jordan", "Greece", "Grenada", "Guatemala",
    "Guinea", "Guinea-Bissau", "Equatorial Guinea", "Guyana",
    "Haiti", "Honduras", "India", "Indonesia",
    "Iran", "Iraq", "Ireland", "Iceland",
    "Israel", "Italy", "Kazakhstan", "Kenya",
    "Kyrgyzstan", "Kiribati", "Kuwait", "Laos",
    "Lesotho", "Latvia", "Lebanon", "Liberia",
    "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "North Macedonia", "Madagascar", "Malawi", "Malaysia",
    "Maldives", "Mali", "Malta", "Morocco",
    "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
    "Micronesia", "Moldova", "Monaco", "Mongolia",
    "Montenegro", "Mozambique", "Namibia", "Nauru",
    "Nepal", "Nicaragua", "Niger", "Nigeria",
    "Norway", "New Zealand", "Oman", "Netherlands",
    "Pakistan", "Palau", "Panama", "Papua New Guinea",
    "Paraguay", "Peru", "Poland", "Portugal",
    "Qatar", "United Kingdom", "Central African Republic", "Czech Republic",
    "Democratic Republic of the Congo", "Republic of the Congo", "Dominican Republic", "Romania",
    "Rwanda", "Russia", "Saint Kitts and Nevis", "Saint Lucia",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Vatican City",
    "São Tomé and Príncipe", "Senegal", "Serbia", "Seychelles",
    "Sierra Leone", "Singapore", "Syria", "Slovakia",
    "Slovenia", "Somalia", "Spain", "Sri Lanka",
    "United States", "South Africa", "Sudan", "South Sudan",
    "Suriname", "Sweden", "Switzerland", "Tajikistan",
    "Taiwan", "Tanzania", "Thailand", "East Timor",
    "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
    "Turkey", "Turkmenistan", "Tuvalu", "Ukraine",
    "Uganda", "Hungary", "Uruguay", "Uzbekistan",
    "Vanuatu", "Venezuela", "Vietnam", "Yemen",
    "Zambia", "Zimbabwe",
]

english_names_lower = [
    "afghanistan", "albania", "algeria", "andorra",
    "angola", "antigua and barbuda", "saudi arabia", "argentina",
    "armenia", "australia", "austria", "azerbaijan",
    "bahamas", "bahrain", "bangladesh", "barbados",
    "belgium", "belize", "benin", "bhutan",
    "belarus", "myanmar", "bolivia", "bosnia and herzegovina",
    "botswana", "brazil", "brunei", "bulgaria",
    "burkina faso", "burundi", "cambodia", "cameroon",
    "canada", "cape verde", "chad", "chile",
    "china", "cyprus", "colombia", "comoros",
    "north korea", "south korea", "ivory coast", "costa rica",
    "croatia", "cuba", "denmark", "dominica",
    "ecuador", "egypt", "el salvador", "united arab emirates",
    "eritrea", "estonia", "eswatini", "ethiopia",
    "fiji", "philippines", "finland", "france",
    "gabon", "gambia", "georgia", "germany",
    "ghana", "jamaica", "japan", "djibouti",
    "jordan", "greece", "grenada", "guatemala",
    "guinea", "guinea-bissau", "equatorial guinea", "guyana",
    "haiti", "honduras", "india", "indonesia",
    "iran", "iraq", "ireland", "iceland",
    "israel", "italy", "kazakhstan", "kenya",
    "kyrgyzstan", "kiribati", "kuwait", "laos",
    "lesotho", "latvia", "lebanon", "liberia",
    "libya", "liechtenstein", "lithuania", "luxembourg",
    "north macedonia", "madagascar", "malawi", "malaysia",
    "maldives", "mali", "malta", "morocco",
    "marshall islands", "mauritania", "mauritius", "mexico",
    "micronesia", "moldova", "monaco", "mongolia",
    "montenegro", "mozambique", "namibia", "nauru",
    "nepal", "nicaragua", "niger", "nigeria",
    "norway", "new zealand", "oman", "netherlands",
    "pakistan", "palau", "panama", "papua new guinea",
    "paraguay", "peru", "poland", "portugal",
    "qatar", "united kingdom", "central african republic", "czech republic",
    "democratic republic of the congo", "republic of the congo", "dominican republic", "romania",
    "rwanda", "russia", "saint kitts and nevis", "saint lucia",
    "saint vincent and the grenadines", "samoa", "san marino", "vatican city",
    "são tomé and príncipe", "senegal", "serbia", "seychelles",
    "sierra leone", "singapore", "syria", "slovakia",
    "slovenia", "somalia", "spain", "sri lanka",
    "united states", "south africa", "sudan", "south sudan",
    "suriname", "sweden", "switzerland", "tajikistan",
    "taiwan", "tanzania", "thailand", "east timor",
    "togo", "tonga", "trinidad and tobago", "tunisia",
    "turkey", "turkmenistan", "tuvalu", "ukraine",
    "uganda", "hungary", "uruguay", "uzbekistan",
    "vanuatu", "venezuela", "vietnam", "yemen",
    "zambia", "zimbabwe"
]

map_flags = {
    "Trinidad and tobago": "Trinidad and Tobago",
    "Antigua and barbuda": "Antigua and Barbuda",
    "Bosnia and herzegovina": "Bosnia and Herzegovina",
    "Democratic republic of the congo": "the Democratic Republic of the Congo",
    "Republic of the congo": "the Republic of the Congo",
    "Saint kitts and nevis": "Saint Kitts and Nevis",
    "Saint vincent and the grenadines": "Saint Vincent and the Grenadines",
    "São tomé and príncipe": "São Tomé and Príncipe",
    "Guinea-bissau": "Guinea-Bissau",
    "Guinea bissau": "Guinea-Bissau",
    "Usa": "Stati Uniti d'America"
}
